### ISSUE TITLE
add rss.xml for rss aggregators

### ISSUE THREAD

**Issue by azbarcea** [alexharv074/alexharv074.github.io#2]
The goal would be to be notified when new articles come.

Would be also handy if the whole article would be in .rss

Great articles!

**Comment by alex-harvey-z3q** [comment]
Hey @azbarcea much appreciated! Do you know of an example rss.xml somewhere as I haven't ever set this up before?

**Comment by alex-harvey-z3q** [comment]
@azbarcea  I have added a feed based on https://github.com/jekyll/jekyll-feed . Since I don't use RSS can you tell me if it works for you? Thanks.

**Comment by alex-harvey-z3q** [comment]
Actually I tested and it's working fine if you go to https://alexharv074.github.io/feed.xml
