### ISSUE TITLE
Thanks for the mention!

### ISSUE THREAD

**Issue by Cinderhaze** [alexharv074/alexharv074.github.io#6]
Was just looking up some info and stumbled onto your post discussing migrating to pdk, and I was reading through your back catalog and found https://alexharv074.github.io/puppet/2018/09/02/pretty-printing-puppet-data.html - I wish we still had a copy of the original ask.puppetlabs.com somewhere, there was a lot of great content, and I probably put that gist together helping someone answer a question on there.  

Hope all is well, it's nice bumping into people across the internet!

**Comment by alex-harvey-z3q** [comment]
Hey @Cinderhaze I am notorious for missing my GitHub notifications! Thanks for this message!
